
<html>
   
   <head>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  
      <title>Menu </title>
   </head>
   
   <body>
      <h1>Bienvenido</h1> 
	  
	  
	<a  class="btn btn-info" href="../controladores/downmusicControlador.php">Comprar canciones</a></li>
	<a  class="btn btn-info" href="../controladores/facturaControlador.php">Mostrar todas las facturas</a></li>
			
	  
      <h2><a href = "../controladores/logoutControlador.php">Cerrar Sesion</a></h2>
   </body>
   
</html>



